# A (PV) is a storage resource provisioned by an admin in the cluster that exists independently of any Pod that might use it. 
# It is a cluster-wide resource that can be dynamically provisioned or statically defined, and has a lifecycle managed by the cluster admin.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data

---
#A PVC is a request for storage by a Pod which consumes PV(s). 
#PVCs provide a way for users to request the storage resources they need.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi