apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers: 
    - name: nginx-test
      image: nginx #docker hub image name
      resources:
        requests:
          memory: "64Mi"  # Minimum memory required
          cpu: "250m"     # Minimum CPU required (250 millicpu)
        limits:
          memory: "128Mi" # Maximum memory allowed
          cpu: "500m"     # Maximum CPU allowed (500 millicpu)