apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: nginx
    type: frontend
    env: production
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"  # Minimum memory required
          cpu: "250m"     # Minimum CPU required (250 millicpu)
        limits:
          memory: "128Mi" # Maximum memory allowed
          cpu: "500m"     # Maximum CPU allowed (500 millicpu)